In [116]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

%matplotlib inline

import warnings
warnings.simplefilter('ignore')

In [117]:
TRAIN_DATASET_PATH = './course_project_train.csv'
TEST_DATASET_PATH = './course_project_test.csv'

In [118]:
df_train = pd.read_csv(TRAIN_DATASET_PATH)

df_test = pd.read_csv(TEST_DATASET_PATH)

df_train.shape, df_test.shape

((7500, 17), (2500, 16))

In [169]:
class Data:
    """Подготовка исходных данных"""
    
    def __init__(self):
        """Параметры класса"""
        self.medians = None
        self.years_mode = None
        self.years_to_numbers = None
        self.Years_of_Credit_History_max = None
        self.Maximum_Open_Credit_min = None
        self.Maximum_Open_Credit_max = None
        self.Current_Loan_Amount_max = None
        self.Credit_Score_max = None
        self.Credit_Score_min = None
        self.Annual_Income_max = None
        self.Months_since_last_delinquent_max = None
        
        
    def fit(self, df):
        
        
        # Расчет медиан
        self.medians = df.median()
        
        
        self.years_mode = df['Years in current job'].mode()[0]
        
        self.years_to_numbers = {'< 1 year': 0,
                                 '1 year': 1,
                                 '2 years': 2,
                                 '3 years': 3,
                                 '4 years': 4,
                                 '5 years': 5,
                                 '6 years': 6,
                                 '7 years': 7,
                                 '8 years': 8,
                                 '9 years': 9,
                                 '10+ years': 10}
        
        self.Years_of_Credit_History_max = 35
        
        self.Annual_Income_max = 3400000
        
        self.Maximum_Open_Credit_min = 4334.0
        self.Maximum_Open_Credit_max = 1400000
        
        self.Months_since_last_delinquent_max = 95
        
        self.Credit_Score_max = 751
        self.Credit_Score_min = 0
        
        self.Current_Loan_Amount_max = 800000
        
        
    def transform(self, df):
        """Трансформация данных"""
            
    # 1. Изменение типа

        # Term, Home Ownership
        df.loc[(df['Home Ownership'] == 'Have Mortgage'), 'Home Ownership'] = 'Home Mortgage' # объединение одинаковых по смыслу свойства признака
        df = pd.get_dummies(df, columns=['Term', 'Home Ownership'])
        
        # Years in current job
        df['Years in current job'].fillna(self.years_mode, inplace=True) # заполнение пропусков наиболее часто встречающимися значениями
        df['Years in current job'].replace(self.years_to_numbers, inplace=True)
        
    
    # 2. Выбросы (outliers)
    
        # Number of Open Accounts
        df.loc[df['Number of Open Accounts'] > 25, 'Number of Open Accounts'] = None
        
        # Months since last delinquent
        df.loc[(df['Months since last delinquent'] > self.Months_since_last_delinquent_max), 'Months since last delinquent'] = None
        
        # Current Credit Balance
        df.loc[(df['Current Credit Balance'] > 800000), 'Current Credit Balance'] = None
    
        # Years of Credit History
        df['Years of Credit History'].clip(upper=self.Years_of_Credit_History_max, axis=0, inplace=True)
        
        # Maximum Open Credit
        df.loc[(df['Maximum Open Credit'] > self.Maximum_Open_Credit_max) | (df['Maximum Open Credit'] < self.Maximum_Open_Credit_min), 'Maximum Open Credit'] = None
        
        # Purpose
        df.loc[(df['Purpose'] != 'debt consolidation') & (df['Purpose'] != 'home improvements'), 'Purpose'] = 'other'
        df = pd.get_dummies(df, columns=['Purpose'])
        
        # Credit Score
        df.loc[(df['Credit Score'] < self.Credit_Score_min) | (df['Credit Score'] > self.Credit_Score_max), 'Credit Score'] = None
    

        # Annual Income
        df.loc[df['Annual Income'] > self.Annual_Income_max, 'Annual Income'] = None
        
        # Current Loan Amount
        df.loc[df['Current Loan Amount'] > self.Current_Loan_Amount_max, 'Current Loan Amount'] = None
        
         
        
    # 3. Пропуски
        
        df.fillna(self.medians, inplace=True)
        
        

        return df

In [170]:
X = df_train.drop(columns='Credit Default')

In [171]:
y = df_train['Credit Default']

In [172]:
from sklearn.model_selection import train_test_split, KFold, GridSearchCV, cross_val_score,  RandomizedSearchCV

# 3. Модели
from sklearn.linear_model import LogisticRegression
import xgboost as xgb, lightgbm as lgbm, catboost as catb
from sklearn.preprocessing import StandardScaler

# 4. Метрики качества
from sklearn.metrics import classification_report, f1_score, precision_score, recall_score

In [173]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, shuffle=False, random_state=42)

In [174]:
data = Data()

In [175]:
data.fit(X_train)

X_train = data.transform(X_train)
X_test = data.transform(X_test)

X_train.isna().sum().sum(), X_test.isna().sum().sum()

(0, 0)

# Нормализация

In [176]:
NUMERIC_FEATURE_NAMES  = X_train.select_dtypes(include={'float', 'int'}).columns.to_list()

In [177]:
NUMERIC_FEATURE_NAMES

['Annual Income',
 'Years in current job',
 'Tax Liens',
 'Number of Open Accounts',
 'Years of Credit History',
 'Maximum Open Credit',
 'Number of Credit Problems',
 'Months since last delinquent',
 'Bankruptcies',
 'Current Loan Amount',
 'Current Credit Balance',
 'Monthly Debt',
 'Credit Score']

In [178]:
scaler = StandardScaler()

def scal(df):
    df_norm = df.copy()
    df_norm[NUMERIC_FEATURE_NAMES] = scaler.fit_transform(df_norm[NUMERIC_FEATURE_NAMES])

    df = df_norm.copy()
    
    return df

In [179]:
X_train = scal(X_train)

In [180]:
X_test = scal(X_test)

# Балансировка

In [181]:
y_train.value_counts()

0    4069
1    1556
Name: Credit Default, dtype: int64

In [182]:
TARGET_NAME = 'Credit Default'

In [183]:
def balance_df_by_target(df, target_name):

    target_counts = df[target_name].value_counts()

    major_class_name = target_counts.argmax()
    minor_class_name = target_counts.argmin()

    disbalance_coeff = int(target_counts[major_class_name] / target_counts[minor_class_name]) - 1

    for i in range(disbalance_coeff):
        sample = df[df[target_name] == minor_class_name].sample(target_counts[minor_class_name])
        df = df.append(sample, ignore_index=True)

    return df.sample(frac=1)

In [184]:
df_for_balancing = pd.concat([X_train, y_train], axis=1)
df_for_balancing

,Annual Income,Years in current job,Tax Liens,Number of Open Accounts,Years of Credit History,Maximum Open Credit,Number of Credit Problems,Months since last delinquent,Bankruptcies,Current Loan Amount,...,Credit Score,Term_Long Term,Term_Short Term,Home Ownership_Home Mortgage,Home Ownership_Own Home,Home Ownership_Rent,Purpose_debt consolidation,Purpose_home improvements,Purpose_other,Credit Default
0,-1.452015,1.087052,-0.115543,0.030046,1.222354,0.604356,1.637151,-0.081160,2.545244,0.000054,...,1.035914,0,1,0,1,0,1,0,0,0
1,-0.419351,1.087052,-0.115543,0.926648,-0.433059,2.295809,-0.341997,-0.081160,-0.337179,-0.253273,...,0.543944,1,0,0,1,0,1,0,0,1
2,-0.940197,0.537715,-0.115543,0.030046,2.531635,2.298211,-0.341997,-0.081160,-0.337179,0.000054,...,0.748932,0,1,1,0,0,1,0,0,0
3,-0.838230,-0.011622,-0.115543,-0.642405,0.650484,-1.233086,1.637151,-0.081160,2.545244,-1.087807,...,-1.218949,0,1,0,1,0,1,0,0,0
4,-0.892968,0.537715,-0.115543,0.478347,-0.688895,-0.419597,1.637151,-0.081160,-0.337179,-1.061976,...,-0.194011,0,1,0,0,1,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5620,0.151141,0.537715,-0.115543,-0.194104,0.304352,-0.202302,-0.341997,-0.081160,-0.337179,-0.862358,...,0.666937,0,1,0,0,1,1,0,0,0
5621,-0.216899,-0.835626,-0.115543,-0.418255,-0.357813,0.334970,-0.341997,0.529439,-0.337179,0.720777,...,0.338956,1,0,1,0,0,1,0,0,1
5622,-0.149739,-0.286290,-0.115543,-0.418255,0.259205,-0.081907,-0.341997,-0.081160,-0.337179,-0.792024,...,0.338956,0,1,1,0,0,1,0,0,0
5623,0.032782,-1.110295,-0.115543,-1.987308,0.274254,-1.211544,-0.341997,-0.081160,-0.337179,0.000054,...,0.789929,1,0,1,0,0,1,0,0,0
5624,-1.488231,-0.560958,-0.115543,-1.314857,-0.809289,-1.309196,-0.341997,-1.302358,-0.337179,-0.949443,...,0.666937,0,1,1,0,0,1,0,0,0

In [185]:
df_balanced = balance_df_by_target(df_for_balancing, TARGET_NAME)
    
df_balanced[TARGET_NAME].value_counts()

0    4069
1    3112
Name: Credit Default, dtype: int64

In [186]:
df_balanced

,Annual Income,Years in current job,Tax Liens,Number of Open Accounts,Years of Credit History,Maximum Open Credit,Number of Credit Problems,Months since last delinquent,Bankruptcies,Current Loan Amount,...,Credit Score,Term_Long Term,Term_Short Term,Home Ownership_Home Mortgage,Home Ownership_Own Home,Home Ownership_Rent,Purpose_debt consolidation,Purpose_home improvements,Purpose_other,Credit Default
6970,3.162512,1.087052,-0.115543,1.150798,1.237403,-0.095343,-0.341997,-0.081160,-0.337179,2.746754,...,0.584942,0,1,1,0,0,1,0,0,1
5978,-1.118169,-1.384963,-0.115543,-0.642405,-0.839387,-1.171763,-0.341997,-0.081160,-0.337179,-1.085122,...,0.051974,0,1,0,0,1,0,0,1,1
3405,1.689811,1.087052,-0.115543,0.254197,1.297600,-0.033494,-0.341997,-0.827448,-0.337179,0.819627,...,-0.153014,1,0,1,0,0,1,0,0,0
4887,-0.948429,-0.835626,-0.115543,0.702498,-1.019978,-0.222568,-0.341997,-0.081160,-0.337179,-0.284987,...,-0.603986,1,0,1,0,0,1,0,0,0
3077,0.794498,1.087052,-0.115543,-0.418255,0.168910,0.005912,-0.341997,0.054529,-0.337179,0.000054,...,0.707934,0,1,1,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2247,1.084150,1.087052,-0.115543,0.926648,2.080159,-0.095343,-0.341997,-0.081160,-0.337179,0.853642,...,1.117909,0,1,1,0,0,1,0,0,0
5230,-0.149739,-0.835626,-0.115543,-1.314857,0.575238,0.541382,-0.341997,-0.081160,-0.337179,-1.470931,...,0.338956,0,1,0,0,1,0,0,1,0
2453,0.719757,-0.560958,-0.115543,1.599099,-0.929683,0.492443,-0.341997,-0.081160,-0.337179,0.720649,...,-0.030021,1,0,1,0,0,1,0,0,1
3700,-1.787450,-1.110295,-0.115543,-1.090706,-1.516602,-1.233311,-0.341997,-0.081160,-0.337179,0.000054,...,0.256961,0,1,0,0,1,1,0,0,0
6919,-0.590427,1.087052,-0.115543,0.702498,0.123762,1.096142,-0.341997,-0.081160,-0.337179,0.724997,...,0.010976,1,0,1,0,0,1,0,0,1

In [187]:
X_train = df_balanced.drop(columns=TARGET_NAME)
y_train = df_balanced[TARGET_NAME]

# Построение модели

In [188]:
def get_classification_report(y_train_true, y_train_pred, y_test_true, y_test_pred):
    print('TRAIN\n\n' + classification_report(y_train_true, y_train_pred))
    print('TEST\n\n' + classification_report(y_test_true, y_test_pred))
    print('CONFUSION MATRIX\n')
    print(pd.crosstab(y_test_true, y_test_pred))

In [189]:
model_catb = catb.CatBoostClassifier(silent=True, random_state=21)
model_catb.fit(X_train, y_train)

y_train_pred = model_catb.predict(X_train)
y_test_pred = model_catb.predict(X_test)

get_classification_report(y_train, y_train_pred, y_test, y_test_pred)

TRAIN

              precision    recall  f1-score   support

           0       0.90      0.93      0.92      4069
           1       0.91      0.87      0.89      3112

    accuracy                           0.90      7181
   macro avg       0.90      0.90      0.90      7181
weighted avg       0.90      0.90      0.90      7181

TEST

              precision    recall  f1-score   support

           0       0.81      0.74      0.77      1318
           1       0.48      0.58      0.53       557

    accuracy                           0.69      1875
   macro avg       0.64      0.66      0.65      1875
weighted avg       0.71      0.69      0.70      1875

CONFUSION MATRIX

col_0             0    1
Credit Default
0               971  347
1               234  323

In [190]:
model_xgb = xgb.XGBClassifier()
model_xgb.fit(X_train, y_train)

y_train_pred = model_xgb.predict(X_train)
y_test_pred = model_xgb.predict(X_test)

get_classification_report(y_train, y_train_pred, y_test, y_test_pred)

[23:29:32] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
TRAIN

              precision    recall  f1-score   support

           0       0.99      0.98      0.99      4069
           1       0.98      0.99      0.98      3112

    accuracy                           0.99      7181
   macro avg       0.99      0.99      0.99      7181
weighted avg       0.99      0.99      0.99      7181

TEST

              precision    recall  f1-score   support

           0       0.79      0.72      0.76      1318
           1       0.46      0.56      0.50       557

    accuracy                           0.67      1875
   macro avg       0.63      0.64      0.63      1875
weighted avg       0.69      0.67      0.68      1875

CONFUSION MATRIX

col_0             0    1
Credit Default
0               952  366
1               247  310

In [191]:
model_lgbm = lgbm.LGBMClassifier(random_state=21)
model_lgbm.fit(X_train, y_train)

y_train_pred = model_lgbm.predict(X_train)
y_test_pred = model_lgbm.predict(X_test)

get_classification_report(y_train, y_train_pred, y_test, y_test_pred)

TRAIN

              precision    recall  f1-score   support

           0       0.92      0.94      0.93      4069
           1       0.92      0.89      0.91      3112

    accuracy                           0.92      7181
   macro avg       0.92      0.92      0.92      7181
weighted avg       0.92      0.92      0.92      7181

TEST

              precision    recall  f1-score   support

           0       0.81      0.69      0.75      1318
           1       0.46      0.62      0.53       557

    accuracy                           0.67      1875
   macro avg       0.64      0.66      0.64      1875
weighted avg       0.71      0.67      0.68      1875

CONFUSION MATRIX

col_0             0    1
Credit Default
0               909  409
1               210  347

In [165]:
model_catb = catb.CatBoostClassifier(silent=True, random_state=21)

In [61]:
# params = {'n_estimators':[50, 100, 200, 300, 400, 500, 1000, 1500, 2000, 2500, 3000], 
#           'max_depth':[3, 4, 5, 6, 7, 8, 10],
#           'learning_rate':[0.001, 0.01, 0.05, 0.1]}

In [62]:
# cv=KFold(n_splits=3, shuffle=True)

In [63]:
# %%time

# rs = GridSearchCV(model_catb, params, scoring='f1', cv=cv, n_jobs=-1)
# rs.fit(X_train, y_train)

In [64]:
# rs.best_params_

In [65]:
# rs.best_score_

In [201]:
%%time

final_model = catb.CatBoostClassifier(n_estimators=500, max_depth=7, learning_rate=0.01,
                                      silent=True)
final_model.fit(X_train, y_train)

y_train_pred = final_model.predict(X_train)
y_test_pred = final_model.predict(X_test)

get_classification_report(y_train, y_train_pred, y_test, y_test_pred)

TRAIN

              precision    recall  f1-score   support

           0       0.78      0.88      0.83      4069
           1       0.82      0.68      0.74      3112

    accuracy                           0.80      7181
   macro avg       0.80      0.78      0.79      7181
weighted avg       0.80      0.80      0.79      7181

TEST

              precision    recall  f1-score   support

           0       0.80      0.77      0.78      1318
           1       0.50      0.55      0.52       557

    accuracy                           0.70      1875
   macro avg       0.65      0.66      0.65      1875
weighted avg       0.71      0.70      0.71      1875

CONFUSION MATRIX

col_0              0    1
Credit Default
0               1011  307
1                251  306
Wall time: 3.76 s

In [196]:
feature_importances = pd.DataFrame(zip(X_train.columns, 
                                       final_model.feature_importances_), 
                                   columns=['feature_name', 'importance'])

feature_importances.sort_values(by='importance', ascending=False, inplace=True)

In [197]:
feature_importances

                    feature_name  importance
9            Current Loan Amount   30.723760
12                  Credit Score   21.400657
0                  Annual Income   10.051666
5            Maximum Open Credit    4.778992
11                  Monthly Debt    4.214347
4        Years of Credit History    4.204810
10        Current Credit Balance    3.812085
1           Years in current job    3.196825
3        Number of Open Accounts    3.033143
14               Term_Short Term    2.809139
13                Term_Long Term    2.725552
7   Months since last delinquent    2.555442
15  Home Ownership_Home Mortgage    1.826129
17           Home Ownership_Rent    1.313270
6      Number of Credit Problems    0.888744
20                 Purpose_other    0.656923
18    Purpose_debt consolidation    0.616682
8                   Bankruptcies    0.583960
2                      Tax Liens    0.250756
19     Purpose_home improvements    0.241587
16       Home Ownership_Own Home    0.115531